name: development pipeline

on:
  push:
    branches:
      - 'develop' # only run on develop branch

jobs:
  development-pipeline:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
      - uses: actions/checkout@v2

      - name: 'Set up Python 3.7'
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: 'Starting task'
        run: echo ">>> Starting task..."

      - name: 'Failing task'
        run: |
          echo ">>> Running tests..."
          exit 1

      - name: 'Validation taks'
        if: github.event_name == "pull_request" && github.event.pull_request.merged == true
        run: echo ">>> Running validation..."
    